Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,21 +14,24 @@ jobs:
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v3  # Use the latest version
+        uses: actions/checkout@v2
 
       - name: Set up Python
-        uses: actions/setup-python@v4  # Use the latest version
+        uses: actions/setup-python@v2
         with:
-          python-version: '3.9'  # Specify the Python version you want
+          python-version: '3.10'
 
       - name: Install necessary packages
         run: pip install requests beautifulsoup4 pandas
 
-      - name: List files  # Debugging step
+      - name: Print working directory
+        run: pwd
+
+      - name: List files
         run: ls -R
 
       - name: Run seafood scraper
-        run: python ./seafood.py || { echo 'Script failed'; exit 1; }  # Running the correct file
+        run: python ./seafood.py || { echo 'Script failed'; exit 1; }
 
       - name: Commit and push CSV file
         run: |
